var k;k||=typeof Immolate != 'undefined' ? Immolate : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=(b,a)=>{throw a;},ea="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ea=__filename:ba&&(ea=self.location.href);var p="",fa,q;
if(ca){var fs=require("fs");p=__dirname+"/";q=b=>{b=t(b)?new URL(b):b;return fs.readFileSync(b)};fa=async b=>{b=t(b)?new URL(b):b;return fs.readFileSync(b,void 0)};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=k);da=(b,a)=>{process.exitCode=b;throw a;}}else if(aa||ba){try{p=(new URL(".",ea)).href}catch{}ba&&(q=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)});fa=async b=>{if(t(b))return new Promise((c,
d)=>{var e=new XMLHttpRequest;e.open("GET",b,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var a=await fetch(b,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}console.log.bind(console);var z=console.error.bind(console),A,ha=!1,t=b=>b.startsWith("file://"),ia,ja,B,C,E,F,G,ka,la,ma,na,J=0,K=null;
function oa(b){k.onAbort?.(b);b="Aborted("+b+")";z(b);ha=!0;throw new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");}var pa;async function qa(b){if(!A)try{var a=await fa(b);return new Uint8Array(a)}catch{}if(b==pa&&A)b=new Uint8Array(A);else if(q)b=q(b);else throw"both async and sync fetching of the wasm failed";return b}async function ra(b,a){try{var c=await qa(b);return await WebAssembly.instantiate(c,a)}catch(d){z(`failed to asynchronously prepare wasm: ${d}`),oa(d)}}
async function sa(b){var a=pa;if(!A&&!t(a)&&!ca)try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){z(`wasm streaming compile failed: ${d}`),z("falling back to ArrayBuffer instantiation")}return ra(a,b)}class ta{name="ExitStatus";constructor(b){this.message=`Program terminated with exit(${b})`;this.status=b}}var ua=b=>{for(;0<b.length;)b.shift()(k)},va=[],wa=[],xa=()=>{var b=k.preRun.shift();wa.push(b)},za=!0;
class Aa{constructor(b){this.G=b-24}}var Ba=0,Ca=0,L=b=>{for(var a="";;){var c=B[b++];if(!c)return a;a+=String.fromCharCode(c)}},M={},N={},O={},P=class extends Error{constructor(b){super(b);this.name="BindingError"}},Da=b=>{throw new P(b);};
function Ea(b,a,c={}){var d=a.name;if(!b)throw new P(`type "${d}" must have a positive integer typeid pointer`);if(N.hasOwnProperty(b)){if(c.ja)return;throw new P(`Cannot register type '${d}' twice`);}N[b]=a;delete O[b];M.hasOwnProperty(b)&&(a=M[b],delete M[b],a.forEach(e=>e()))}function Q(b,a,c={}){return Ea(b,a,c)}
var Fa=(b,a,c)=>{switch(a){case 1:return c?d=>ja[d]:d=>B[d];case 2:return c?d=>C[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];case 8:return c?d=>ma[d>>3]:d=>na[d>>3];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Ga=b=>{throw new P(b.D.H.F.name+" instance already deleted");},Ha=!1,Ia=()=>{},R=b=>{if("undefined"===typeof FinalizationRegistry)return R=a=>a,b;Ha=new FinalizationRegistry(a=>{a=a.D;--a.count.value;0===a.count.value&&(a.K?a.N.S(a.K):a.H.F.S(a.G))});R=a=>
{var c=a.D;c.K&&Ha.register(a,{D:c},a);return a};Ia=a=>{Ha.unregister(a)};return R(b)},Ja=[];function S(){}
var Ka=(b,a)=>Object.defineProperty(a,"name",{value:b}),La={},Ma=(b,a,c)=>{if(void 0===b[a].J){var d=b[a];b[a]=function(...e){if(!b[a].J.hasOwnProperty(e.length))throw new P(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].J})!`);return b[a].J[e.length].apply(this,e)};b[a].J=[];b[a].J[d.U]=d}},Na=(b,a,c)=>{if(k.hasOwnProperty(b)){if(void 0===c||void 0!==k[b].J&&void 0!==k[b].J[c])throw new P(`Cannot register public name '${b}' twice`);Ma(k,b,b);if(k[b].J.hasOwnProperty(c))throw new P(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
k[b].J[c]=a}else k[b]=a,k[b].U=c},Oa=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function Pa(b,a,c,d,e,f,h,g){this.name=b;this.constructor=a;this.R=c;this.S=d;this.L=e;this.ha=f;this.X=h;this.ga=g;this.la=[]}
var T=(b,a,c)=>{for(;a!==c;){if(!a.X)throw new P(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.X(b);a=a.L}return b},Qa=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b};
function Ra(b,a){if(null===a){if(this.$)throw new P(`null is not a valid ${this.name}`);return 0}if(!a.D)throw new P(`Cannot pass "${Qa(a)}" as a ${this.name}`);if(!a.D.G)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);return T(a.D.G,a.D.H.F,this.F)}
function Sa(b,a){if(null===a){if(this.$)throw new P(`null is not a valid ${this.name}`);if(this.Z){var c=this.ma();null!==b&&b.push(this.S,c);return c}return 0}if(!a||!a.D)throw new P(`Cannot pass "${Qa(a)}" as a ${this.name}`);if(!a.D.G)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Y&&a.D.H.Y)throw new P(`Cannot convert argument of type ${a.D.N?a.D.N.name:a.D.H.name} to parameter type ${this.name}`);c=T(a.D.G,a.D.H.F,this.F);if(this.Z){if(void 0===a.D.K)throw new P("Passing raw pointer to smart pointer is illegal");
switch(this.oa){case 0:if(a.D.N===this)c=a.D.K;else throw new P(`Cannot convert argument of type ${a.D.N?a.D.N.name:a.D.H.name} to parameter type ${this.name}`);break;case 1:c=a.D.K;break;case 2:if(a.D.N===this)c=a.D.K;else{var d=a.clone();c=this.na(c,Ta(()=>d["delete"]()));null!==b&&b.push(this.S,c)}break;default:throw new P("Unsupporting sharing policy");}}return c}
function Ua(b,a){if(null===a){if(this.$)throw new P(`null is not a valid ${this.name}`);return 0}if(!a.D)throw new P(`Cannot pass "${Qa(a)}" as a ${this.name}`);if(!a.D.G)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.D.H.Y)throw new P(`Cannot convert argument of type ${a.D.H.name} to parameter type ${this.name}`);return T(a.D.G,a.D.H.F,this.F)}function Va(b){return this.I(G[b>>2])}
var Wa=(b,a,c)=>{if(a===c)return b;if(void 0===c.L)return null;b=Wa(b,a,c.L);return null===b?null:c.ga(b)},Xa={},Ya=(b,a)=>{if(void 0===a)throw new P("ptr should not be undefined");for(;b.L;)a=b.X(a),b=b.L;return Xa[a]},Za=class extends Error{constructor(b){super(b);this.name="InternalError"}},$a=(b,a)=>{if(!a.H||!a.G)throw new Za("makeClassHandle requires ptr and ptrType");if(!!a.N!==!!a.K)throw new Za("Both smartPtrType and smartPtr must be specified");a.count={value:1};return R(Object.create(b,
{D:{value:a,writable:!0}}))};function ab(b,a,c,d,e,f,h,g,l,n,m){this.name=b;this.F=a;this.$=c;this.Y=d;this.Z=e;this.ka=f;this.oa=h;this.ea=g;this.ma=l;this.na=n;this.S=m;e||void 0!==a.L?this.M=Sa:(this.M=d?Ra:Ua,this.O=null)}
var bb=(b,a,c)=>{if(!k.hasOwnProperty(b))throw new Za("Replacing nonexistent public symbol");void 0!==k[b].J&&void 0!==c?k[b].J[c]=a:(k[b]=a,k[b].U=c)},cb=[],db,U=(b,a)=>{b=L(b);var c;(c=cb[a])||(cb[a]=c=db.get(a));if("function"!=typeof c)throw new P(`unknown function pointer with signature ${b}: ${a}`);return c};class eb extends Error{}
var hb=b=>{b=fb(b);var a=L(b);V(b);return a},W=(b,a)=>{function c(f){e[f]||N[f]||(O[f]?O[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};a.forEach(c);throw new eb(`${b}: `+d.map(hb).join([", "]));},X=(b,a,c)=>{function d(g){g=c(g);if(g.length!==b.length)throw new Za("Mismatched type converter count");for(var l=0;l<b.length;++l)Q(b[l],g[l])}b.forEach(g=>O[g]=a);var e=Array(a.length),f=[],h=0;a.forEach((g,l)=>{N.hasOwnProperty(g)?e[l]=N[g]:(f.push(g),M.hasOwnProperty(g)||(M[g]=[]),M[g].push(()=>{e[l]=
N[g];++h;h===f.length&&d(e)}))});0===f.length&&d(e)},ib=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(G[a+4*d>>2]);return c},jb=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function kb(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].O)return!0;return!1}
function lb(b,a,c,d,e,f){var h=a.length;if(2>h)throw new P("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==a[1]&&null!==c,l=kb(a);c=!a[0].da;var n=a[0],m=a[1];d=[b,Da,d,e,jb,n.I.bind(n),m?.M.bind(m)];for(e=2;e<h;++e)n=a[e],d.push(n.M.bind(n));if(!l)for(e=g?1:2;e<a.length;++e)null!==a[e].O&&d.push(a[e].O);l=kb(a);e=a.length-2;m=[];n=["fn"];g&&n.push("thisWired");for(h=0;h<e;++h)m.push(`arg${h}`),n.push(`arg${h}Wired`);m=m.join(",");n=n.join(",");m=`return function (${m}) {\n`;
l&&(m+="var destructors = [];\n");var u=l?"destructors":"null",w="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");g&&(m+=`var thisWired = toClassParamWire(${u}, this);\n`);for(h=0;h<e;++h){var r=`toArg${h}Wire`;m+=`var arg${h}Wired = ${r}(${u}, arg${h});\n`;w.push(r)}m+=(c||f?"var rv = ":"")+`invoker(${n});\n`;if(l)m+="runDestructors(destructors);\n";else for(h=g?1:2;h<a.length;++h)f=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==a[h].O&&(m+=`${f}_dtor(${f});\n`,
w.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");a=(new Function(w,m+"}\n"))(...d);return Ka(b,a)}
var mb=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},nb=(b,a,c)=>{if(!(b instanceof Object))throw new P(`${c} with invalid "this": ${b}`);if(!(b instanceof a.F.constructor))throw new P(`${c} incompatible with "this" of type ${b.constructor.name}`);if(!b.D.G)throw new P(`cannot call emscripten binding method ${c} on deleted object`);return T(b.D.G,b.D.H.F,a.F)},ob=[],Y=[0,1,,1,null,1,!0,1,!1,1],pb=b=>{9<b&&0===--Y[b+1]&&(Y[b]=void 0,ob.push(b))},qb=b=>{if(!b)throw new P(`Cannot use deleted val. handle = ${b}`);
return Y[b]},Ta=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=ob.pop()||Y.length;Y[a]=b;Y[a+1]=1;return a}},rb={name:"emscripten::val",I:b=>{var a=qb(b);pb(b);return a},M:(b,a)=>Ta(a),P:Va,O:null},sb=(b,a)=>{switch(a){case 4:return function(c){return this.I(ka[c>>2])};case 8:return function(c){return this.I(la[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);}},tb=Object.assign({optional:!0},rb),ub="undefined"!=typeof TextDecoder?
new TextDecoder:void 0,vb=(b,a,c,d)=>{c=a+c;if(d)return c;for(;b[a]&&!(a>=c);)++a;return a},wb=(b=0,a)=>{var c=B;a=vb(c,b,a,!0);if(16<a-b&&c.buffer&&ub)return ub.decode(c.subarray(b,a));for(var d="";b<a;){var e=c[b++];if(e&128){var f=c[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=c[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|c[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
xb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,yb=(b,a,c)=>{b>>=1;a=vb(E,b,a/2,c);if(16<a-b&&xb)return xb.decode(E.subarray(b,a));for(c="";b<a;++b)c+=String.fromCharCode(E[b]);return c},zb=(b,a,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)C[a>>1]=b.charCodeAt(e),a+=2;C[a>>1]=0;return a-d},Ab=b=>2*b.length,Bb=(b,a,c)=>{var d="";b>>=2;for(var e=0;!(e>=a/4);e++){var f=G[b+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},
Cb=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var f=b.codePointAt(e);65535<f&&e++;F[a>>2]=f;a+=4;if(a+4>c)break}F[a>>2]=0;return a-d},Db=b=>{for(var a=0,c=0;c<b.length;++c)65535<b.codePointAt(c)&&c++,a+=4;return a},Eb=[],Fb=b=>{var a=Eb.length;Eb.push(b);return a},Gb=(b,a)=>{for(var c=Array(b),d=0;d<b;++d){var e=d,f=G[a+4*d>>2],h=N[f];if(void 0===h)throw b=`${`parameter ${d}`} has unknown type ${hb(f)}`,new P(b);c[e]=h}return c},Hb=(b,a,c)=>{var d=[];b=b(d,
c);d.length&&(G[a>>2]=Ta(d));return b},Ib={},Jb=b=>{var a=Ib[b];return void 0===a?L(b):a};
(()=>{let b=S.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof S&&c instanceof S))return!1;var d=this.D.H.F,e=this.D.G;c.D=c.D;var f=c.D.H.F;for(c=c.D.G;d.L;)e=d.X(e),d=d.L;for(;f.L;)c=f.X(c),f=f.L;return d===f&&e===c},clone:function(){this.D.G||Ga(this);if(this.D.W)return this.D.count.value+=1,this;var c=R,d=Object,e=d.create,f=Object.getPrototypeOf(this),h=this.D;c=c(e.call(d,f,{D:{value:{count:h.count,V:h.V,W:h.W,G:h.G,H:h.H,K:h.K,N:h.N}}}));c.D.count.value+=1;c.D.V=!1;return c},
["delete"](){this.D.G||Ga(this);if(this.D.V&&!this.D.W)throw new P("Object already scheduled for deletion");Ia(this);var c=this.D;--c.count.value;0===c.count.value&&(c.K?c.N.S(c.K):c.H.F.S(c.G));this.D.W||(this.D.K=void 0,this.D.G=void 0)},isDeleted:function(){return!this.D.G},deleteLater:function(){this.D.G||Ga(this);if(this.D.V&&!this.D.W)throw new P("Object already scheduled for deletion");Ja.push(this);this.D.V=!0;return this}});const a=Symbol.dispose;a&&(b[a]=b["delete"])})();
Object.assign(ab.prototype,{ia(b){this.ea&&(b=this.ea(b));return b},ba(b){this.S?.(b)},P:Va,I:function(b){function a(){return this.Z?$a(this.F.R,{H:this.ka,G:c,N:this,K:b}):$a(this.F.R,{H:this,G:b})}var c=this.ia(b);if(!c)return this.ba(b),null;var d=Ya(this.F,c);if(void 0!==d){if(0===d.D.count.value)return d.D.G=c,d.D.K=b,d.clone();d=d.clone();this.ba(b);return d}d=this.F.ha(c);d=La[d];if(!d)return a.call(this);d=this.Y?d.fa:d.pointerType;var e=Wa(c,this.F,d.F);return null===e?a.call(this):this.Z?
$a(d.F.R,{H:d,G:e,N:this,K:b}):$a(d.F.R,{H:d,G:e})}});k.noExitRuntime&&(za=k.noExitRuntime);k.printErr&&(z=k.printErr);k.wasmBinary&&(A=k.wasmBinary);
var fb,Kb,Lb,V,Mb={l:(b,a,c)=>{var d=new Aa(b);G[d.G+16>>2]=0;G[d.G+4>>2]=a;G[d.G+8>>2]=c;Ba=b;Ca++;throw Ba;},p:()=>oa(""),o:(b,a,c,d,e)=>{a=L(a);d=0n===d;let f=h=>h;if(d){const h=8*c;f=g=>BigInt.asUintN(h,g);e=f(e)}Q(b,{name:a,I:f,M:(h,g)=>{"number"==typeof g&&(g=BigInt(g));return g},P:Fa(a,c,!d),O:null})},u:(b,a,c,d)=>{a=L(a);Q(b,{name:a,I:function(e){return!!e},M:function(e,f){return f?c:d},P:function(e){return this.I(B[e])},O:null})},f:(b,a,c,d,e,f,h,g,l,n,m,u,w)=>{m=L(m);f=U(e,f);g&&=U(h,g);
n&&=U(l,n);w=U(u,w);var r=Oa(m);Na(r,function(){W(`Cannot construct ${m} due to unbound types`,[d])});X([b,a,c],d?[d]:[],v=>{v=v[0];if(d){var x=v.F;var H=x.R}else H=S.prototype;v=Ka(m,function(...ya){if(Object.getPrototypeOf(this)!==I)throw new P(`Use 'new' to construct ${m}`);if(void 0===y.T)throw new P(`${m} has no accessible constructor`);var gb=y.T[ya.length];if(void 0===gb)throw new P(`Tried to invoke ctor of ${m} with invalid number of parameters (${ya.length}) - expected (${Object.keys(y.T).toString()}) parameters instead!`);
return gb.apply(this,ya)});var I=Object.create(H,{constructor:{value:v}});v.prototype=I;var y=new Pa(m,v,I,w,x,f,g,n);if(y.L){var D;(D=y.L).aa??(D.aa=[]);y.L.aa.push(y)}x=new ab(m,y,!0,!1,!1);D=new ab(m+"*",y,!1,!1,!1);H=new ab(m+" const*",y,!1,!0,!1);La[b]={pointerType:D,fa:H};bb(r,v);return[x,D,H]})},c:(b,a,c,d,e,f)=>{var h=ib(a,c);e=U(d,e);X([],[b],g=>{g=g[0];var l=`constructor ${g.name}`;void 0===g.F.T&&(g.F.T=[]);if(void 0!==g.F.T[a-1])throw new P(`Cannot register multiple constructors with identical number of parameters (${a-
1}) for class '${g.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);g.F.T[a-1]=()=>{W(`Cannot construct ${g.name} due to unbound types`,h)};X([],h,n=>{n.splice(1,0,null);g.F.T[a-1]=lb(l,n,null,e,f);return[]});return[]})},a:(b,a,c,d,e,f,h,g,l)=>{var n=ib(c,d);a=L(a);a=mb(a);f=U(e,f);X([],[b],m=>{function u(){W(`Cannot call ${w} due to unbound types`,n)}m=m[0];var w=`${m.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);g&&m.F.la.push(a);
var r=m.F.R,v=r[a];void 0===v||void 0===v.J&&v.className!==m.name&&v.U===c-2?(u.U=c-2,u.className=m.name,r[a]=u):(Ma(r,a,w),r[a].J[c-2]=u);X([],n,x=>{x=lb(w,x,m,f,h,l);void 0===r[a].J?(x.U=c-2,r[a]=x):r[a].J[c-2]=x;return[]});return[]})},b:(b,a,c,d,e,f,h,g,l,n)=>{a=L(a);e=U(d,e);X([],[b],m=>{m=m[0];var u=`${m.name}.${a}`,w={get(){W(`Cannot access ${u} due to unbound types`,[c,h])},enumerable:!0,configurable:!0};w.set=l?()=>W(`Cannot access ${u} due to unbound types`,[c,h]):()=>{throw new P(u+" is a read-only property");
};Object.defineProperty(m.F.R,a,w);X([],l?[c,h]:[c],r=>{var v=r[0],x={get(){var I=nb(this,m,u+" getter");return v.I(e(f,I))},enumerable:!0};if(l){l=U(g,l);var H=r[1];x.set=function(I){var y=nb(this,m,u+" setter"),D=[];l(n,y,H.M(D,I));jb(D)}}Object.defineProperty(m.F.R,a,x);return[]});return[]})},s:b=>Q(b,rb),n:(b,a,c)=>{a=L(a);Q(b,{name:a,I:d=>d,M:(d,e)=>e,P:sb(a,c),O:null})},e:(b,a,c,d,e,f,h)=>{var g=ib(a,c);b=L(b);b=mb(b);e=U(d,e);Na(b,function(){W(`Cannot call ${b} due to unbound types`,g)},a-
1);X([],g,l=>{l=[l[0],null].concat(l.slice(1));bb(b,lb(b,l,null,e,f,h),a-1);return[]})},g:(b,a,c,d,e)=>{a=L(a);let f=g=>g;if(0===d){var h=32-8*c;f=g=>g<<h>>>h;e=f(e)}Q(b,{name:a,I:f,M:(g,l)=>l,P:Fa(a,c,0!==d),O:null})},d:(b,a,c)=>{function d(f){return new e(ja.buffer,G[f+4>>2],G[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=L(c);Q(b,{name:c,I:d,P:d},{ja:!0})},k:b=>{Q(b,tb)},t:(b,a)=>{a=L(a);Q(b,{name:a,
I(c){var d=(d=c+4)?wb(d,G[c>>2]):"";V(c);return d},M(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f="string"==typeof d;if(!(f||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new P("Cannot pass non-string to std::string");var h;if(f)for(e=h=0;e<d.length;++e){var g=d.charCodeAt(e);127>=g?h++:2047>=g?h+=2:55296<=g&&57343>=g?(h+=4,++e):h+=3}else h=d.length;e=h;h=Kb(4+e+1);g=h+4;G[h>>2]=e;if(f){if(f=g,g=e+1,e=B,0<g){g=f+g-1;for(var l=0;l<d.length;++l){var n=d.codePointAt(l);if(127>=
n){if(f>=g)break;e[f++]=n}else if(2047>=n){if(f+1>=g)break;e[f++]=192|n>>6;e[f++]=128|n&63}else if(65535>=n){if(f+2>=g)break;e[f++]=224|n>>12;e[f++]=128|n>>6&63;e[f++]=128|n&63}else{if(f+3>=g)break;e[f++]=240|n>>18;e[f++]=128|n>>12&63;e[f++]=128|n>>6&63;e[f++]=128|n&63;l++}}e[f]=0}}else B.set(d,g);null!==c&&c.push(V,h);return h},P:Va,O(c){V(c)}})},m:(b,a,c)=>{c=L(c);if(2===a){var d=yb;var e=zb;var f=Ab}else d=Bb,e=Cb,f=Db;Q(b,{name:c,I:h=>{var g=d(h+4,G[h>>2]*a,!0);V(h);return g},M:(h,g)=>{if("string"!=
typeof g)throw new P(`Cannot pass non-string to C++ string type ${c}`);var l=f(g),n=Kb(4+l+a);G[n>>2]=l/a;e(g,n+4,l+a);null!==h&&h.push(V,n);return n},P:Va,O(h){V(h)}})},v:(b,a)=>{a=L(a);Q(b,{da:!0,name:a,I:()=>{},M:()=>{}})},j:(b,a,c)=>{var [d,...e]=Gb(b,a);a=d.M.bind(d);var f=e.map(l=>l.P.bind(l));b--;var h={toValue:qb};b=f.map((l,n)=>{var m=`argFromPtr${n}`;h[m]=l;return`${m}(args${n?"+"+8*n:""})`});switch(c){case 0:var g="toValue(handle)";break;case 2:g="new (toValue(handle))";break;case 3:g=
"";break;case 1:h.getStringOrSymbol=Jb,g="toValue(handle)[getStringOrSymbol(methodName)]"}g+=`(${b})`;d.da||(h.toReturnWire=a,h.emval_returnValue=Hb,g=`return emval_returnValue(toReturnWire, destructorsRef, ${g})`);g=`return function (handle, methodName, destructorsRef, args) {\n  ${g}\n  }`;c=(new Function(Object.keys(h),g))(...Object.values(h));g=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;return Fb(Ka(g,c))},i:(b,a,c,d,e)=>Eb[b](a,c,d,e),h:b=>{var a=qb(b);jb(a);pb(b)},r:()=>Date.now(),q:()=>
{oa("OOM")}},Z;
(async function(){function b(c){Z=c.exports;ia=Z.w;c=ia.buffer;ja=new Int8Array(c);C=new Int16Array(c);B=new Uint8Array(c);E=new Uint16Array(c);F=new Int32Array(c);G=new Uint32Array(c);ka=new Float32Array(c);la=new Float64Array(c);ma=new BigInt64Array(c);na=new BigUint64Array(c);db=Z.z;c=Z;fb=c.y;Kb=c.A;k._main=Lb=c.B;V=c.C;J--;k.monitorRunDependencies?.(J);0==J&&K&&(c=K,K=null,c());return Z}J++;k.monitorRunDependencies?.(J);var a={a:Mb};if(k.instantiateWasm)return new Promise(c=>{k.instantiateWasm(a,(d,
e)=>{c(b(d,e))})});pa??=k.locateFile?k.locateFile("immolate.wasm",p):p+"immolate.wasm";return b((await sa(a)).instance)})();
function Nb(){function b(){k.calledRun=!0;if(!ha){Z.x();k.onRuntimeInitialized?.();if(!k.noInitialRun){var a=Lb;try{var c=a(0,0);za||(k.onExit?.(c),ha=!0);da(c,new ta(c))}catch(d){d instanceof ta||"unwind"==d||da(1,d)}}if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;)a=k.postRun.shift(),va.push(a);ua(va)}}if(0<J)K=Nb;else{if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)xa();ua(wa);0<J?K=Nb:k.setStatus?(k.setStatus("Running..."),
setTimeout(()=>{setTimeout(()=>k.setStatus(""),1);b()},1)):b()}}if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.shift()();Nb();
