var n;n||=typeof Immolate != 'undefined' ? Immolate : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=(b,a)=>{throw a;},ea="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ea=__filename:ba&&(ea=self.location.href);var p="",fa,u;
if(ca){var fs=require("fs");p=__dirname+"/";u=b=>{b=v(b)?new URL(b):b;return fs.readFileSync(b)};fa=async b=>{b=v(b)?new URL(b):b;return fs.readFileSync(b,void 0)};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=n);da=(b,a)=>{process.exitCode=b;throw a;}}else if(aa||ba){try{p=(new URL(".",ea)).href}catch{}ba&&(u=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)});fa=async b=>{if(v(b))return new Promise((c,
d)=>{var e=new XMLHttpRequest;e.open("GET",b,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var a=await fetch(b,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}console.log.bind(console);var z=console.error.bind(console),A,ha=!1,v=b=>b.startsWith("file://"),ia,ja,C,E,G,H,I,ka,la,ma,na,J=0,K=null;
function oa(b){n.onAbort?.(b);b="Aborted("+b+")";z(b);ha=!0;throw new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");}var pa;async function qa(b){if(!A)try{var a=await fa(b);return new Uint8Array(a)}catch{}if(b==pa&&A)b=new Uint8Array(A);else if(u)b=u(b);else throw"both async and sync fetching of the wasm failed";return b}async function ra(b,a){try{var c=await qa(b);return await WebAssembly.instantiate(c,a)}catch(d){z(`failed to asynchronously prepare wasm: ${d}`),oa(d)}}
async function sa(b){var a=pa;if(!A&&"function"==typeof WebAssembly.instantiateStreaming&&!v(a)&&!ca)try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){z(`wasm streaming compile failed: ${d}`),z("falling back to ArrayBuffer instantiation")}return ra(a,b)}class ta{name="ExitStatus";constructor(b){this.message=`Program terminated with exit(${b})`;this.status=b}}
var ua=b=>{for(;0<b.length;)b.shift()(n)},va=[],wa=[],xa=()=>{var b=n.preRun.shift();wa.push(b)},ya=!0;class Aa{constructor(b){this.I=b-24}}var Ba=0,Ca=0,L={},M=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function N(b){return this.K(I[b>>2])}
var O={},P={},Da={},Ea=class extends Error{constructor(b){super(b);this.name="InternalError"}},R=(b,a,c)=>{function d(f){f=c(f);if(f.length!==b.length)throw new Ea("Mismatched type converter count");for(var k=0;k<b.length;++k)Q(b[k],f[k])}b.forEach(f=>Da[f]=a);var e=Array(a.length),g=[],h=0;a.forEach((f,k)=>{P.hasOwnProperty(f)?e[k]=P[f]:(g.push(f),O.hasOwnProperty(f)||(O[f]=[]),O[f].push(()=>{e[k]=P[f];++h;h===g.length&&d(e)}))});0===g.length&&d(e)},S=b=>{for(var a="";;){var c=C[b++];if(!c)return a;
a+=String.fromCharCode(c)}},T=class extends Error{constructor(b){super(b);this.name="BindingError"}},Fa=b=>{throw new T(b);};function Ga(b,a,c={}){var d=a.name;if(!b)throw new T(`type "${d}" must have a positive integer typeid pointer`);if(P.hasOwnProperty(b)){if(c.pa)return;throw new T(`Cannot register type '${d}' twice`);}P[b]=a;delete Da[b];O.hasOwnProperty(b)&&(a=O[b],delete O[b],a.forEach(e=>e()))}function Q(b,a,c={}){return Ga(b,a,c)}
var Ha=(b,a,c)=>{switch(a){case 1:return c?d=>ja[d]:d=>C[d];case 2:return c?d=>E[d>>1]:d=>G[d>>1];case 4:return c?d=>H[d>>2]:d=>I[d>>2];case 8:return c?d=>ma[d>>3]:d=>na[d>>3];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Ia=b=>{throw new T(b.G.J.H.name+" instance already deleted");},Ja=!1,Ka=()=>{},U=b=>{if("undefined"===typeof FinalizationRegistry)return U=a=>a,b;Ja=new FinalizationRegistry(a=>{a=a.G;--a.count.value;0===a.count.value&&(a.M?a.R.S(a.M):a.J.H.S(a.I))});U=a=>
{var c=a.G;c.M&&Ja.register(a,{G:c},a);return a};Ka=a=>{Ja.unregister(a)};return U(b)},La=[];function Ma(){}
var Na=(b,a)=>Object.defineProperty(a,"name",{value:b}),Oa={},Pa=(b,a,c)=>{if(void 0===b[a].L){var d=b[a];b[a]=function(...e){if(!b[a].L.hasOwnProperty(e.length))throw new T(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].L})!`);return b[a].L[e.length].apply(this,e)};b[a].L=[];b[a].L[d.W]=d}},Qa=(b,a,c)=>{if(n.hasOwnProperty(b)){if(void 0===c||void 0!==n[b].L&&void 0!==n[b].L[c])throw new T(`Cannot register public name '${b}' twice`);Pa(n,b,b);if(n[b].L.hasOwnProperty(c))throw new T(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
n[b].L[c]=a}else n[b]=a,n[b].W=c},Ra=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function Sa(b,a,c,d,e,g,h,f){this.name=b;this.constructor=a;this.U=c;this.S=d;this.O=e;this.ka=g;this.Z=h;this.ja=f;this.ra=[]}
var Ta=(b,a,c)=>{for(;a!==c;){if(!a.Z)throw new T(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.Z(b);a=a.O}return b},Ua=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b};
function Va(b,a){if(null===a){if(this.ba)throw new T(`null is not a valid ${this.name}`);return 0}if(!a.G)throw new T(`Cannot pass "${Ua(a)}" as a ${this.name}`);if(!a.G.I)throw new T(`Cannot pass deleted object as a pointer of type ${this.name}`);return Ta(a.G.I,a.G.J.H,this.H)}
function Wa(b,a){if(null===a){if(this.ba)throw new T(`null is not a valid ${this.name}`);if(this.aa){var c=this.da();null!==b&&b.push(this.S,c);return c}return 0}if(!a||!a.G)throw new T(`Cannot pass "${Ua(a)}" as a ${this.name}`);if(!a.G.I)throw new T(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.$&&a.G.J.$)throw new T(`Cannot convert argument of type ${a.G.R?a.G.R.name:a.G.J.name} to parameter type ${this.name}`);c=Ta(a.G.I,a.G.J.H,this.H);if(this.aa){if(void 0===a.G.M)throw new T("Passing raw pointer to smart pointer is illegal");
switch(this.wa){case 0:if(a.G.R===this)c=a.G.M;else throw new T(`Cannot convert argument of type ${a.G.R?a.G.R.name:a.G.J.name} to parameter type ${this.name}`);break;case 1:c=a.G.M;break;case 2:if(a.G.R===this)c=a.G.M;else{var d=a.clone();c=this.sa(c,Xa(()=>d["delete"]()));null!==b&&b.push(this.S,c)}break;default:throw new T("Unsupporting sharing policy");}}return c}
function Ya(b,a){if(null===a){if(this.ba)throw new T(`null is not a valid ${this.name}`);return 0}if(!a.G)throw new T(`Cannot pass "${Ua(a)}" as a ${this.name}`);if(!a.G.I)throw new T(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.G.J.$)throw new T(`Cannot convert argument of type ${a.G.J.name} to parameter type ${this.name}`);return Ta(a.G.I,a.G.J.H,this.H)}
var Za=(b,a,c)=>{if(a===c)return b;if(void 0===c.O)return null;b=Za(b,a,c.O);return null===b?null:c.ja(b)},$a={},ab=(b,a)=>{if(void 0===a)throw new T("ptr should not be undefined");for(;b.O;)a=b.Z(a),b=b.O;return $a[a]},bb=(b,a)=>{if(!a.J||!a.I)throw new Ea("makeClassHandle requires ptr and ptrType");if(!!a.R!==!!a.M)throw new Ea("Both smartPtrType and smartPtr must be specified");a.count={value:1};return U(Object.create(b,{G:{value:a,writable:!0}}))};
function cb(b,a,c,d,e,g,h,f,k,m,l){this.name=b;this.H=a;this.ba=c;this.$=d;this.aa=e;this.qa=g;this.wa=h;this.ha=f;this.da=k;this.sa=m;this.S=l;e||void 0!==a.O?this.N=Wa:(this.N=d?Va:Ya,this.P=null)}
var db=(b,a,c)=>{if(!n.hasOwnProperty(b))throw new Ea("Replacing nonexistent public symbol");void 0!==n[b].L&&void 0!==c?n[b].L[c]=a:(n[b]=a,n[b].W=c)},eb=[],fb,V=(b,a)=>{b=S(b);var c;(c=eb[a])||(eb[a]=c=fb.get(a));if("function"!=typeof c)throw new T(`unknown function pointer with signature ${b}: ${a}`);return c};class gb extends Error{}
var jb=b=>{b=ib(b);var a=S(b);W(b);return a},X=(b,a)=>{function c(g){e[g]||P[g]||(Da[g]?Da[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};a.forEach(c);throw new gb(`${b}: `+d.map(jb).join([", "]));},kb=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(I[a+4*d>>2]);return c};function lb(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].P)return!0;return!1}
function mb(b,a,c,d,e,g){var h=a.length;if(2>h)throw new T("argTypes array size mismatch! Must at least get return value and 'this' types!");var f=null!==a[1]&&null!==c,k=lb(a);c=!a[0].ga;var m=a[0],l=a[1];d=[b,Fa,d,e,M,m.K.bind(m),l?.N.bind(l)];for(e=2;e<h;++e)m=a[e],d.push(m.N.bind(m));if(!k)for(e=f?1:2;e<a.length;++e)null!==a[e].P&&d.push(a[e].P);k=lb(a);e=a.length-2;l=[];m=["fn"];f&&m.push("thisWired");for(h=0;h<e;++h)l.push(`arg${h}`),m.push(`arg${h}Wired`);l=l.join(",");m=m.join(",");l=`return function (${l}) {\n`;
k&&(l+="var destructors = [];\n");var q=k?"destructors":"null",w="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");f&&(l+=`var thisWired = toClassParamWire(${q}, this);\n`);for(h=0;h<e;++h){var r=`toArg${h}Wire`;l+=`var arg${h}Wired = ${r}(${q}, arg${h});\n`;w.push(r)}l+=(c||g?"var rv = ":"")+`invoker(${m});\n`;if(k)l+="runDestructors(destructors);\n";else for(h=f?1:2;h<a.length;++h)g=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==a[h].P&&(l+=`${g}_dtor(${g});\n`,
w.push(`${g}_dtor`));c&&(l+="var ret = fromRetWire(rv);\nreturn ret;\n");a=(new Function(w,l+"}\n"))(...d);return Na(b,a)}
var nb=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},ob=(b,a,c)=>{if(!(b instanceof Object))throw new T(`${c} with invalid "this": ${b}`);if(!(b instanceof a.H.constructor))throw new T(`${c} incompatible with "this" of type ${b.constructor.name}`);if(!b.G.I)throw new T(`cannot call emscripten binding method ${c} on deleted object`);return Ta(b.G.I,b.G.J.H,a.H)},pb=[],Y=[0,1,,1,null,1,!0,1,!1,1],qb=b=>{9<b&&0===--Y[b+1]&&(Y[b]=void 0,pb.push(b))},rb=b=>{if(!b)throw new T(`Cannot use deleted val. handle = ${b}`);
return Y[b]},Xa=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=pb.pop()||Y.length;Y[a]=b;Y[a+1]=1;return a}},sb={name:"emscripten::val",K:b=>{var a=rb(b);qb(b);return a},N:(b,a)=>Xa(a),T:N,P:null},tb=(b,a)=>{switch(a){case 4:return function(c){return this.K(ka[c>>2])};case 8:return function(c){return this.K(la[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);}},ub=Object.assign({optional:!0},sb),vb="undefined"!=typeof TextDecoder?
new TextDecoder:void 0,wb=(b,a,c,d)=>{c=a+c;if(d)return c;for(;b[a]&&!(a>=c);)++a;return a},xb=(b=0,a)=>{var c=C;a=wb(c,b,a,!0);if(16<a-b&&c.buffer&&vb)return vb.decode(c.subarray(b,a));for(var d="";b<a;){var e=c[b++];if(e&128){var g=c[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=c[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|c[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
yb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,zb=(b,a,c)=>{b>>=1;a=wb(G,b,a/2,c);if(16<a-b&&yb)return yb.decode(G.subarray(b,a));for(c="";b<a;++b)c+=String.fromCharCode(G[b]);return c},Ab=(b,a,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)E[a>>1]=b.charCodeAt(e),a+=2;E[a>>1]=0;return a-d},Bb=b=>2*b.length,Cb=(b,a,c)=>{var d="";b>>=2;for(var e=0;!(e>=a/4);e++){var g=I[b+e];if(!g&&!c)break;d+=String.fromCodePoint(g)}return d},
Db=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var g=b.codePointAt(e);65535<g&&e++;H[a>>2]=g;a+=4;if(a+4>c)break}H[a>>2]=0;return a-d},Eb=b=>{for(var a=0,c=0;c<b.length;++c)65535<b.codePointAt(c)&&c++,a+=4;return a},Fb=[],Gb=b=>{var a=Fb.length;Fb.push(b);return a},Hb=(b,a)=>{for(var c=Array(b),d=0;d<b;++d){var e=d,g=I[a+4*d>>2],h=P[g];if(void 0===h)throw b=`${`parameter ${d}`} has unknown type ${jb(g)}`,new T(b);c[e]=h}return c},Ib=(b,a,c)=>{var d=[];b=b(d,
c);d.length&&(I[a>>2]=Xa(d));return b},Jb={},Kb=b=>{var a=Jb[b];return void 0===a?S(b):a};
(()=>{let b=Ma.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof Ma&&c instanceof Ma))return!1;var d=this.G.J.H,e=this.G.I;c.G=c.G;var g=c.G.J.H;for(c=c.G.I;d.O;)e=d.Z(e),d=d.O;for(;g.O;)c=g.Z(c),g=g.O;return d===g&&e===c},clone:function(){this.G.I||Ia(this);if(this.G.Y)return this.G.count.value+=1,this;var c=U,d=Object,e=d.create,g=Object.getPrototypeOf(this),h=this.G;c=c(e.call(d,g,{G:{value:{count:h.count,X:h.X,Y:h.Y,I:h.I,J:h.J,M:h.M,R:h.R}}}));c.G.count.value+=1;c.G.X=!1;
return c},["delete"](){this.G.I||Ia(this);if(this.G.X&&!this.G.Y)throw new T("Object already scheduled for deletion");Ka(this);var c=this.G;--c.count.value;0===c.count.value&&(c.M?c.R.S(c.M):c.J.H.S(c.I));this.G.Y||(this.G.M=void 0,this.G.I=void 0)},isDeleted:function(){return!this.G.I},deleteLater:function(){this.G.I||Ia(this);if(this.G.X&&!this.G.Y)throw new T("Object already scheduled for deletion");La.push(this);this.G.X=!0;return this}});const a=Symbol.dispose;a&&(b[a]=b["delete"])})();
Object.assign(cb.prototype,{la(b){this.ha&&(b=this.ha(b));return b},fa(b){this.S?.(b)},T:N,K:function(b){function a(){return this.aa?bb(this.H.U,{J:this.qa,I:c,R:this,M:b}):bb(this.H.U,{J:this,I:b})}var c=this.la(b);if(!c)return this.fa(b),null;var d=ab(this.H,c);if(void 0!==d){if(0===d.G.count.value)return d.G.I=c,d.G.M=b,d.clone();d=d.clone();this.fa(b);return d}d=this.H.ka(c);d=Oa[d];if(!d)return a.call(this);d=this.$?d.ia:d.pointerType;var e=Za(c,this.H,d.H);return null===e?a.call(this):this.aa?
bb(d.H.U,{J:d,I:e,R:this,M:b}):bb(d.H.U,{J:d,I:e})}});n.noExitRuntime&&(ya=n.noExitRuntime);n.printErr&&(z=n.printErr);n.wasmBinary&&(A=n.wasmBinary);
var ib,Lb,Mb,W,Nb={m:(b,a,c)=>{var d=new Aa(b);I[d.I+16>>2]=0;I[d.I+4>>2]=a;I[d.I+8>>2]=c;Ba=b;Ca++;throw Ba;},s:()=>oa(""),q:b=>{var a=L[b];delete L[b];var c=a.elements,d=c.length,e=c.map(f=>f.oa).concat(c.map(f=>f.ua)),g=a.da,h=a.S;R([b],e,f=>{c.forEach((k,m)=>{var l=f[m],q=k.ma,w=k.na,r=f[m+d],t=k.ta,x=k.va;k.read=B=>l.K(q(w,B));k.write=(B,D)=>{var y=[];t(x,B,r.N(y,D));M(y)}});return[{name:a.name,K:k=>{for(var m=Array(d),l=0;l<d;++l)m[l]=c[l].read(k);h(k);return m},N:(k,m)=>{if(d!==m.length)throw new TypeError(`Incorrect number of tuple elements for ${a.name}: expected=${d}, actual=${m.length}`);
for(var l=g(),q=0;q<d;++q)c[q].write(l,m[q]);null!==k&&k.push(h,l);return l},T:N,P:h}]})},p:(b,a,c,d,e)=>{a=S(a);d=0n===d;let g=h=>h;if(d){const h=8*c;g=f=>BigInt.asUintN(h,f);e=g(e)}Q(b,{name:a,K:g,N:(h,f)=>{"number"==typeof f&&(f=BigInt(f));return f},T:Ha(a,c,!d),P:null})},x:(b,a,c,d)=>{a=S(a);Q(b,{name:a,K:function(e){return!!e},N:function(e,g){return g?c:d},T:function(e){return this.K(C[e])},P:null})},f:(b,a,c,d,e,g,h,f,k,m,l,q,w)=>{l=S(l);g=V(e,g);f&&=V(h,f);m&&=V(k,m);w=V(q,w);var r=Ra(l);Qa(r,
function(){X(`Cannot construct ${l} due to unbound types`,[d])});R([b,a,c],d?[d]:[],t=>{t=t[0];if(d){var x=t.H;var B=x.U}else B=Ma.prototype;t=Na(l,function(...za){if(Object.getPrototypeOf(this)!==D)throw new T(`Use 'new' to construct ${l}`);if(void 0===y.V)throw new T(`${l} has no accessible constructor`);var hb=y.V[za.length];if(void 0===hb)throw new T(`Tried to invoke ctor of ${l} with invalid number of parameters (${za.length}) - expected (${Object.keys(y.V).toString()}) parameters instead!`);
return hb.apply(this,za)});var D=Object.create(B,{constructor:{value:t}});t.prototype=D;var y=new Sa(l,t,D,w,x,g,f,m);if(y.O){var F;(F=y.O).ea??(F.ea=[]);y.O.ea.push(y)}x=new cb(l,y,!0,!1,!1);F=new cb(l+"*",y,!1,!1,!1);B=new cb(l+" const*",y,!1,!0,!1);Oa[b]={pointerType:F,ia:B};db(r,t);return[x,F,B]})},c:(b,a,c,d,e,g)=>{var h=kb(a,c);e=V(d,e);R([],[b],f=>{f=f[0];var k=`constructor ${f.name}`;void 0===f.H.V&&(f.H.V=[]);if(void 0!==f.H.V[a-1])throw new T(`Cannot register multiple constructors with identical number of parameters (${a-
1}) for class '${f.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);f.H.V[a-1]=()=>{X(`Cannot construct ${f.name} due to unbound types`,h)};R([],h,m=>{m.splice(1,0,null);f.H.V[a-1]=mb(k,m,null,e,g);return[]});return[]})},a:(b,a,c,d,e,g,h,f,k)=>{var m=kb(c,d);a=S(a);a=nb(a);g=V(e,g);R([],[b],l=>{function q(){X(`Cannot call ${w} due to unbound types`,m)}l=l[0];var w=`${l.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);f&&l.H.ra.push(a);
var r=l.H.U,t=r[a];void 0===t||void 0===t.L&&t.className!==l.name&&t.W===c-2?(q.W=c-2,q.className=l.name,r[a]=q):(Pa(r,a,w),r[a].L[c-2]=q);R([],m,x=>{x=mb(w,x,l,g,h,k);void 0===r[a].L?(x.W=c-2,r[a]=x):r[a].L[c-2]=x;return[]});return[]})},b:(b,a,c,d,e,g,h,f,k,m)=>{a=S(a);e=V(d,e);R([],[b],l=>{l=l[0];var q=`${l.name}.${a}`,w={get(){X(`Cannot access ${q} due to unbound types`,[c,h])},enumerable:!0,configurable:!0};w.set=k?()=>X(`Cannot access ${q} due to unbound types`,[c,h]):()=>{throw new T(q+" is a read-only property");
};Object.defineProperty(l.H.U,a,w);R([],k?[c,h]:[c],r=>{var t=r[0],x={get(){var D=ob(this,l,q+" getter");return t.K(e(g,D))},enumerable:!0};if(k){k=V(f,k);var B=r[1];x.set=function(D){var y=ob(this,l,q+" setter"),F=[];k(m,y,B.N(F,D));M(F)}}Object.defineProperty(l.H.U,a,x);return[]});return[]})},v:b=>Q(b,sb),o:(b,a,c)=>{a=S(a);Q(b,{name:a,K:d=>d,N:(d,e)=>e,T:tb(a,c),P:null})},e:(b,a,c,d,e,g,h)=>{var f=kb(a,c);b=S(b);b=nb(b);e=V(d,e);Qa(b,function(){X(`Cannot call ${b} due to unbound types`,f)},a-1);
R([],f,k=>{k=[k[0],null].concat(k.slice(1));db(b,mb(b,k,null,e,g,h),a-1);return[]})},g:(b,a,c,d,e)=>{a=S(a);let g=f=>f;if(0===d){var h=32-8*c;g=f=>f<<h>>>h;e=g(e)}Q(b,{name:a,K:g,N:(f,k)=>k,T:Ha(a,c,0!==d),P:null})},d:(b,a,c)=>{function d(g){return new e(ja.buffer,I[g+4>>2],I[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=S(c);Q(b,{name:c,K:d,T:d},{pa:!0})},h:b=>{Q(b,ub)},w:(b,a)=>{a=S(a);Q(b,{name:a,K(c){var d=
(d=c+4)?xb(d,I[c>>2]):"";W(c);return d},N(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,g="string"==typeof d;if(!(g||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new T("Cannot pass non-string to std::string");var h;if(g)for(e=h=0;e<d.length;++e){var f=d.charCodeAt(e);127>=f?h++:2047>=f?h+=2:55296<=f&&57343>=f?(h+=4,++e):h+=3}else h=d.length;e=h;h=Lb(4+e+1);f=h+4;I[h>>2]=e;if(g){if(g=f,f=e+1,e=C,0<f){f=g+f-1;for(var k=0;k<d.length;++k){var m=d.codePointAt(k);if(127>=m){if(g>=f)break;
e[g++]=m}else if(2047>=m){if(g+1>=f)break;e[g++]=192|m>>6;e[g++]=128|m&63}else if(65535>=m){if(g+2>=f)break;e[g++]=224|m>>12;e[g++]=128|m>>6&63;e[g++]=128|m&63}else{if(g+3>=f)break;e[g++]=240|m>>18;e[g++]=128|m>>12&63;e[g++]=128|m>>6&63;e[g++]=128|m&63;k++}}e[g]=0}}else C.set(d,f);null!==c&&c.push(W,h);return h},T:N,P(c){W(c)}})},n:(b,a,c)=>{c=S(c);if(2===a){var d=zb;var e=Ab;var g=Bb}else d=Cb,e=Db,g=Eb;Q(b,{name:c,K:h=>{var f=d(h+4,I[h>>2]*a,!0);W(h);return f},N:(h,f)=>{if("string"!=typeof f)throw new T(`Cannot pass non-string to C++ string type ${c}`);
var k=g(f),m=Lb(4+k+a);I[m>>2]=k/a;e(f,m+4,k+a);null!==h&&h.push(W,m);return m},T:N,P(h){W(h)}})},r:(b,a,c,d,e,g)=>{L[b]={name:S(a),da:V(c,d),S:V(e,g),elements:[]}},i:(b,a,c,d,e,g,h,f,k)=>{L[b].elements.push({oa:a,ma:V(c,d),na:e,ua:g,ta:V(h,f),va:k})},y:(b,a)=>{a=S(a);Q(b,{ga:!0,name:a,K:()=>{},N:()=>{}})},l:(b,a,c)=>{var [d,...e]=Hb(b,a);a=d.N.bind(d);var g=e.map(k=>k.T.bind(k));b--;var h={toValue:rb};b=g.map((k,m)=>{var l=`argFromPtr${m}`;h[l]=k;return`${l}(args${m?"+"+8*m:""})`});switch(c){case 0:var f=
"toValue(handle)";break;case 2:f="new (toValue(handle))";break;case 3:f="";break;case 1:h.getStringOrSymbol=Kb,f="toValue(handle)[getStringOrSymbol(methodName)]"}f+=`(${b})`;d.ga||(h.toReturnWire=a,h.emval_returnValue=Ib,f=`return emval_returnValue(toReturnWire, destructorsRef, ${f})`);f=`return function (handle, methodName, destructorsRef, args) {\n  ${f}\n  }`;c=(new Function(Object.keys(h),f))(...Object.values(h));f=`methodCaller<(${e.map(k=>k.name)}) => ${d.name}>`;return Gb(Na(f,c))},k:(b,a,
c,d,e)=>Fb[b](a,c,d,e),j:b=>{var a=rb(b);M(a);qb(b)},u:()=>Date.now(),t:()=>{oa("OOM")}},Z;
(async function(){function b(c){Z=c.exports;ia=Z.z;c=ia.buffer;ja=new Int8Array(c);E=new Int16Array(c);C=new Uint8Array(c);G=new Uint16Array(c);H=new Int32Array(c);I=new Uint32Array(c);ka=new Float32Array(c);la=new Float64Array(c);ma=new BigInt64Array(c);na=new BigUint64Array(c);fb=Z.C;c=Z;ib=c.B;Lb=c.D;n._main=Mb=c.E;W=c.F;J--;n.monitorRunDependencies?.(J);0==J&&K&&(c=K,K=null,c());return Z}J++;n.monitorRunDependencies?.(J);var a={a:Nb};if(n.instantiateWasm)return new Promise(c=>{n.instantiateWasm(a,
(d,e)=>{c(b(d,e))})});pa??=n.locateFile?n.locateFile("immolate.wasm",p):p+"immolate.wasm";return b((await sa(a)).instance)})();
function Ob(){function b(){n.calledRun=!0;if(!ha){Z.A();n.onRuntimeInitialized?.();if(!n.noInitialRun){var a=Mb;try{var c=a(0,0);ya||(n.onExit?.(c),ha=!0);da(c,new ta(c))}catch(d){d instanceof ta||"unwind"==d||da(1,d)}}if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;)a=n.postRun.shift(),va.push(a);ua(va)}}if(0<J)K=Ob;else{if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)xa();ua(wa);0<J?K=Ob:n.setStatus?(n.setStatus("Running..."),
setTimeout(()=>{setTimeout(()=>n.setStatus(""),1);b()},1)):b()}}if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.shift()();Ob();
